### PR TITLE
Generate struct field docstrings

### PR DESCRIPTION
**Pull request by yejia-stripe**
## Summary
Remove pre-codegen comments and generate struct field docstrings from the OpenAPI spec.

VSCode documentation popup
Screen Shot 2022-01-14 at 1 19 45 PM

Preview using the [godoc](https://pkg.go.dev/golang.org/x/tools/cmd/godoc) tool
Screen Shot 2022-01-14 at 1 44 49 PM

## Notify
r? @richardm-stripe
cc @dcr-stripe

### CODE REVIEW

**Comment by richardm-stripe** [comment]
Can you add a couple screenshots to the PR description, of how this will appear to e.g. a vscode user. Do they get these docstrings on mouseover? Also I'm curious how this would appear in [godoc](https://pkg.go.dev/github.com/stripe/stripe-go/v72), I'm not an expert but I think you can generate the godoc .html files using the godoc CLI and it would be good to take a look.

Particularly, I'm curious how the markdown links in our docstrings render.

**Review by richardm-stripe — CHANGES_REQUESTED** [review]
(Just wanted to ask for screenshots in the PR description)

**Comment by yejia-stripe** [comment]
I don't think it's possible to have the link text be different from the URL

**Review by richardm-stripe — APPROVED** [review]

**Pull request merged**
