### PR TITLE
Make invoice items a slice, as per API spec

### PR DESCRIPTION
**Pull request by EVODelavega**
Quick fix for the package, seems to be what is required for this particular call to work

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Oh shoot. Thank you @EVODelavega!

@remi-stripe Thoughts on bumping this as minor? It probably didn't work before anyway (and definitely didn't work correctly even if it technically ran).

**Comment by remi-stripe** [comment]
@brandur-stripe Yes I think it makes sense here to bump as a minor and call it out in the changelog!

**Comment by EVODelavega** [comment]
@brandur-stripe Yeah, would really appreciate this fix to land ASAP. Previewing an upcoming invoice and adding an invoice item (only 1, because that's all you could add) results in a 400 response. I've tried the same request with this change, everything worked like a charm

**Comment by remi-stripe** [comment]
Can I let you release this one to unblock @EVODelavega?

**Comment by brandur-stripe** [comment]
@remi-stripe Yep, I got it.

**Comment by brandur-stripe** [comment]
Released as 57.1.0.

**Pull request merged**
