### PR TITLE
Add BillingCycleAnchor to SubParams

### LINKED ISSUE #105: Sub: billing_cycle_anchor field
Can we add the (undocumented but often-referred-to) billing_cycle_anchor field to SubParams?

### PR DESCRIPTION
**Pull request by shazow**
Resolves #105

### CODE REVIEW

**Comment by shazow** [comment]
FYI this lacks tests. I'm on super-flakey conference wifi at the moment so I haven't been able to run the api test suite yet. Let me know if that's a blocker.

**Comment by cosn** [comment]
yeah, tests would be nice ... once added I'm happy to merge

thanks!

**Comment by shazow** [comment]
@cosn Added a test.

**Comment by cosn** [comment]
Thanks!

**Pull request merged**
