### PR TITLE
Added support for outcome[rule] on Charge object

### PR DESCRIPTION
**Pull request by remi-stripe**
r? @brandur-stripe

I haven't been able to add tests for this because in Test mode that hash seems to always been empty.

### CODE REVIEW

**Comment by brandur** [comment]
> I haven't been able to add tests for this because in Test mode that hash seems to always been empty.

I think the Go bindings use a different test account, so it may be some sort of gating issue. Honestly, I wouldn't worry about it too much.

LGTM, but would you mind adding a short comment to the new struct of the form "ChargeOutcomeRule is ...". We're still a little ways off it, but it would be nice to eventually turn the Linter on for this project.

**Comment by remi-stripe** [comment]
> I think the Go bindings use a different test account, so it may be some sort of gating issue. Honestly, I wouldn't worry about it too much.

I think that it's mainly available in Live mode only specifically.

> would you mind adding a short comment to the new struct of the form "ChargeOutcomeRule is ...". 

will do!

**Comment by remi-stripe** [comment]
PTAL

**Comment by brandur** [comment]
> I think that it's mainly available in Live mode only specifically.

Ah yes, that sounds plausible.

Looks great. Thanks!

**Comment by brandur** [comment]
Released as 19.2.0.

**Pull request merged**
