### PR TITLE
Make invoiceitem/client.go codegen-able

### PR DESCRIPTION
**Pull request by yejia-stripe**
## Summary
Formatting changes only

## Notify
r? @richardm-stripe 
cc @dcr-stripe

### CODE REVIEW

**Review by richardm-stripe — APPROVED** [review]

**Review by bungfut — COMMENTED** [review]
<removed>

**Comment by bungfut** [comment]
https://github.com/stripe/stripe-go/pull/1346.patch

**Comment by bungfut** [comment]
GH-26

**Comment by PANDURANGAN321** [comment]
Y

**Pull request merged**
