### PR TITLE
Add webhook signing

### LINKED ISSUE #405: Webhook signature verification
Hi, I think it would be useful if this library verified webhook event signatures.  Here's how I implemented it:

```go
import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"strings"
)

// checkSignature verifies a Stripe-Signature header from webhook.
// It returns an error if the signature is missing or invalid, or nil if the signature is OK.
// NOTE: stripe only sends signatures when you have clicked to reveal your secret
// The secret is a hex byte slice of the string generated by stripe.
// The body is the webhook request's body.
// The header is the webhook request's Stripe-Signature header.
func checkSignature(secret, body []byte, header string) error {
        // First extract the timestamp
	var timestamp string
	pairs := strings.Split(header, ",")
	for _, pair := range pairs {
		parts := strings.Split(pair, "=")
		if parts[0] == "t" {
			timestamp = parts[1]
			break
		}
	}

	if timestamp == "" {
		return errors.New("Missing timestamp")
	}

	mac := hmac.New(sha256.New, secret)
	mac.Write([]byte(timestamp))
	mac.Write([]byte("."))
	mac.Write(body)
	res := mac.Sum(nil)

	// Check all v1 signatures (multiple v1 can happen in case of rolled secret).
	for _, pair := range pairs {
		parts := strings.Split(pair, "=")
		if parts[0] != "v1" {
			continue
		}

		sig, err := hex.DecodeString(parts[1])
		if err != nil {
			return err
		}

		if hmac.Equal(res, sig) {
			return nil
		}
	}

	return errors.New("Correct signature not found")
}
```

Usage looks like:

```go
func stripeWebhooks(w http.ResponseWriter, r *http.Request) {
        secret := byte[]("whsec_XYZ")
	body, _ := ioutil.ReadAll(r.Body)
        header := r.Header.Get("Stripe-Signature")
        if err := checkSignature(secret, body, header); err != nil {
                http.Error(w, "Missing/invalid signature", http.StatusBadRequest)
                return
        }
```

Happy to make a PR if this looks OK and if you can guide on how API should look :).

### PR DESCRIPTION
**Pull request by fred-stripe**
Fixes #405 based on @froatsnook's excellent work in #413. Added a test suite based on other libraries' tests, refactored the public interface, and updated the godocs.

r? @brandur-stripe @ob-stripe 

I want to add one additional test as I think it's not fully testing multiple signatures behavior.

### CODE REVIEW

**Comment by ob-stripe** [comment]
Awesome! Thanks @fred-stripe (and thanks again @froatsnook).

- I don't feel too strongly about this but I think the `testmode` part based on detecting `v0` signatures is unnecessary. The event itself already has a `livemode` attribute, and while it's true that `v0` signatures are only sent for test mode events, their purpose is not specifically to indicate test mode but rather to allow you to verify that your integration ignores signatures with unexpected schemes

-  could we rename the methods from `ValidateEvent` to `ConstructEvent`, to be consistent with other languages implementations?

Aside from that, lgtm!

**Comment by brandur-stripe** [comment]
Nice work! Looks good to me as well.

Quick question: is `ConstructEventIgnoringTolerance` expected to be useful for something? It seems like it might be something that could be used accidentally, and whether we should consider just not even providing it.

**Comment by fred-stripe** [comment]
Hmm, the only way this would be useful would be validating stale signed requests long after the fact (say you stored all webhook requests in a file or database somewhere). I'm not sure that it's a really valid usecase, as the better approach would be to note that they had valid signatures when they arrived and reject those that aren't helpful.

The ability to ignore timestamp tolerances seems to be available in `stripe-ruby` as well, so I'm tempted to keep it in this implementation:

https://github.com/stripe/stripe-ruby/blob/master/lib/stripe/webhook.rb#L69-L73

I also rather fancy `ConstructEventIgnoringTolerance` as a method name, similar to `dangerouslySetInnerHTML` in React—that is, "you _can_ do this but you should think about what you're doing."

**Comment by brandur-stripe** [comment]
Alright, works for me!

**Comment by brandur-stripe** [comment]
Released as 22.5.0.

**Pull request merged**
