### PR TITLE
return sublist items

### PR DESCRIPTION
**Pull request by nathanjsweet**

### CODE REVIEW

**Comment by nathanjsweet** [comment]
Sorry that I neglected this in my last PR. I'm actually running this code now and can confirm that this is the last issue, from a code perspective, around the SubList stuff.

**Comment by brandur-stripe** [comment]
Thanks again!

**Comment by brandur-stripe** [comment]
Released as 22.4.1.

**Comment by nathanjsweet** [comment]
Thanks! You are really on top of things.

**Pull request merged**
