### PR TITLE
Use interface for logger

### PR DESCRIPTION
**Pull request by discordianfish**
Hi,

I want to propose this simple change which allows people to specify their own logger. All calls to the logger are already only using Printf, so that's all a logger is required to implement.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
> I want to propose this simple change which allows people to specify their own logger.

Can you elaborate on this further? It seems like you can already specify your own logger.

I'm somewhat amenable to the change if there's a good reason, but by default we should probably stick with standard Go conventions here.

**Comment by discordianfish** [comment]
@brandur-stripe Right now you can only specify an instance of log.Logger, while there are many other, very common logger implementations (like logrus which I'm using). I don't feel very strongly since I could also use a log.Logger instance which writes to my 3rd party logger, but using interfaces seems to me the more idiomatic way. Then again, not sure how others are doing this.

**Comment by brandur-stripe** [comment]
Thanks for the context! I poked around with a few of our Go people here, and it seems that this is fairly uncontroversial given a lack of a better solution from the standard library. Thanks for the patch.

**Comment by brandur-stripe** [comment]
Released as 22.1.0.

**Pull request merged**
