### PR TITLE
Support expansion of products in plans

### PR DESCRIPTION
**Pull request by majelbstoat**
per @remi-stripe, should fix https://github.com/stripe/stripe-go/issues/692.

### CODE REVIEW

**Comment by remi-stripe** [comment]
@majelbstoat Thanks for opening the PR so quickly :)

r? @brandur-stripe to make sure it's correct and release. I think this is a breaking change so tagging as such.
cc @stripe/api-libraries

**Comment by brandur-stripe** [comment]
LGTM!

> I think this is a breaking change so tagging as such.

Yep, agreed.

**Comment by brandur-stripe** [comment]
Thanks @majelbstoat!

Released as 49.0.0.

**Comment by majelbstoat** [comment]
Thanks folks! (This work sponsored by [ClassPass](https://github.com/classpass) ❤️)

**Pull request merged**
