### PR TITLE
Resolves issue with unescaped coupon ids

### PR DESCRIPTION
**Pull request by ssoroka**
Closes issue https://github.com/stripe/stripe-go/issues/278

### CODE REVIEW

**Comment by brandur** [comment]
Thanks @ssoroka!

LGTM!

Travis seems to be having a bit of trouble right now, but I'm going to wait a bit longer before merging to see if we can get a green there.

**Comment by brandur** [comment]
@ssoroka Actually, mind taking a look at the build? I think just some missing imports:

```
$ make
go test -run "TestCheckin*" ./client
# github.com/stripe/stripe-go/coupon
coupon/client.go:88: undefined: url in url.QueryEscape
coupon/client.go:105: undefined: url in url.QueryEscape
coupon/client.go:118: undefined: url in url.QueryEscape
# github.com/stripe/stripe-go/plan
plan/client.go:73: undefined: url in url.QueryEscape
plan/client.go:104: undefined: url in url.QueryEscape
plan/client.go:117: undefined: url in url.QueryEscape
FAIL	github.com/stripe/stripe-go/client [build failed]
make: *** [checkin] Error 2
```

**Comment by ssoroka** [comment]
k.

**Comment by brandur** [comment]
Thanks!

LGTM.

**Comment by brandur** [comment]
Released as v16.3.1.

**Pull request merged**
