### PR TITLE
Accounts can be marked with 0 additional owners

### PR DESCRIPTION
**Pull request by Oralordos**
I fixed the ability to unset additional owners on managed accounts.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Amazing. We owe you another one @Oralordos!

**Comment by brandur-stripe** [comment]
Hold on one few minutes before using this maybe (until I cut a release). I think I might refactor it slightly.

**Comment by brandur-stripe** [comment]
Hi @Oralordos, I hope it's okay with you, but I think I'm going to tweak this slightly so that we re-use a convention introduced under `Customer` that allows a field to be emptied with a field suffixed with `Empty`. Sorry I didn't catch it earlier, but it only occurred to me after I hit "merge". See #377.

**Comment by Oralordos** [comment]
Works for me. I think the code I am making for managed accounts is done now. Everything else seemed to work.

**Comment by brandur-stripe** [comment]
> Works for me. I think the code I am making for managed accounts is done now. Everything else seemed to work.

Cool. And that's relieving to hear! Thanks for the quick response.

Just released this as 19.13.0.

**Pull request merged**
