### PR TITLE
Extended Sub Update with CouponRemove

### PR DESCRIPTION
**Pull request by layby42**
pull request for https://github.com/stripe/stripe-go/issues/370

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Hi @layby42, thank you so much for the PR!

Sorry for the nitpick, but would you mind changing the naming to `CouponEmpty`? I think that way we could then more plausibly apply it to other parameters in the future where we want to allow a string to be set to an empty value. I'm actually a little surprised that we don't seem to have a convention for this already. Thanks!

**Comment by layby42** [comment]
Hi @brandur-stripe, renamed

**Comment by remi-stripe** [comment]
@layby42 we just released a change in the API allowing to do the same thing on the Customer Update [API](https://stripe.com/docs/api#update_customer-coupon). Any chance you could add this feature in your PR too?

**Comment by layby42** [comment]
@brandur-stripe we do not need it for customer, at least not now, but we do need it for subscription and we need it now. I can add the same for customer, I guess.

**Comment by remi-stripe** [comment]
@layby42 if you could bundle it in your PR that would be awesome as it's the same feature just on a different model. No worries if you don't though I can add it later otherwise.

**Comment by layby42** [comment]
@remi-stripe done

**Comment by remi-stripe** [comment]
LGTM

I'll let @brandur-stripe do the merge + release early next week though. Thank you so much for working on this so quickly!

**Comment by brandur-stripe** [comment]
Nice! Thanks for making those changes @layby42! Bringing this in.

**Comment by brandur-stripe** [comment]
Released as 19.10.0.

**Pull request merged**
