### PR TITLE
Add expandable Application to Charge

### PR DESCRIPTION
**Pull request by dpetrovics-stripe**
Adds `Application` to `Charge`. Added some basic deserialization tests and added an expansion for an existing functional test.

r? @brandur

### CODE REVIEW

**Comment by brandur** [comment]
@dpetrovics-stripe Looking good!

One other thing I think you might want is a custom JSON deserializer that will expand conditionally like this one:
https://github.com/stripe/stripe-go/blob/84484ce43b9b0edbdfde86a4c8f9d082df9e3638/charge.go#L158,L173

That way even if an application is _not_ expanded, the ID will still be injected into an otherwise blank struct.

ptal @dpetrovics-stripe

**Comment by dpetrovics-stripe** [comment]
Ah, yes - my oversight. Added!

ptal @brandur

**Comment by brandur** [comment]
LGTM.

Thanks @dpetrovics-stripe!

**Comment by dpetrovics-stripe** [comment]
Released as `18.9.0`

**Pull request merged**
