### PR TITLE
Ship changes to the Payment Intent resource

### PR DESCRIPTION
**Pull request by remi-stripe**
The Payment Intent resource had some changes. This PR addresses all the changes. This will be released as a major version and we will automatically return the old shape based on previous stripe-go versions.

cc @danwang-stripe @stripe/api-libraries 
r? @brandur-stripe

### CODE REVIEW

**Comment by brandur-stripe** [comment]
LGTM.

**Comment by brandur-stripe** [comment]
Arg, I think the core team has dropped support for 1.8 in the HTTP/2 package :/

It's not great to drop 1.8 from our matrix so soon after 1.7, but technically the Go team doesn't support it, and since they've now broken compatibility, we might not have a choice.

**Comment by remi-stripe** [comment]
@brandur-stripe yeah do we have stats on how many people use Go 1.8?

**Comment by brandur-stripe** [comment]
@remi-stripe Just under 10% :/

**Comment by remi-stripe** [comment]
That seems really high to drop support for it. Is the issue fixable?

**Comment by brandur-stripe** [comment]
> That seems really high to drop support for it. Is the issue fixable?

Barring trying to lobby the core team to not break old versions or dropping HTTP/2 support, unfortunately I don't think so.

The good news is that upgrades in Go are _way_ easier than almost any other language. 10% may be a lot, but I don't think they're going to experience any significant lock in to 1.8.

**Comment by remi-stripe** [comment]
@brandur-stripe Can I leave to you to open a separate PR for dropping support? Or should we do it in the same PR?

**Comment by brandur-stripe** [comment]
@remi-stripe Yeah, I can open one. Just sec.

**Comment by brandur-stripe** [comment]
@remi-stripe #716 should probably have a major release, and so should this, so I didn't release for the time being so that we can roll these up together.

**Comment by remi-stripe** [comment]
@brandur-stripe While working on other additions I discovered another thing I missed before and this made me rethink the way I do params on Payment Intents. We now have one struct for create/update and then one struct per endpoint (to match what we did on invoices in the other PR).

Can you re-review?

**Comment by brandur-stripe** [comment]
@remi-stripe Yeah, I like the new approach better and it's good that it's more consistent — sorry I missed it before too.

LGTM.

**Pull request merged**
