### PR TITLE
added some more fields

### PR DESCRIPTION
**Pull request by tejasmanohar**

### CODE REVIEW

**Comment by brandur** [comment]
Thanks! Mind just alphabetizing this list since it's largely ordered already?

**Comment by tejasmanohar** [comment]
@brandur sure done

**Comment by brandur** [comment]
Thanks!

LGTM.

**Comment by brandur** [comment]
Oh, actually, I don't think you pushed the update and I didn't check it. I'll fix in master.

**Comment by tejasmanohar** [comment]
ah darn, git push didn't go through 😞  - thx

**Pull request merged**
