### PR TITLE
Enforce linter on all files and packages

### PR DESCRIPTION
**Pull request by remi-stripe**
This enforces the linter on all files and packages and fixes all the current errors

* Fix the makefile to run `golint ./...`
* Add comments to all const blocks to describe what they represent
* Fix comments on all structs and exported methods
* A few breaking changes due to naming of properties or variables:
  * `Account` resource where `IdentityVerificationDetailsCodeScanIdCountryNotSupported` is now `IdentityVerificationDetailsCodeScanIDCountryNotSupported`
  * `Account` resource where `IdentityVerificationDetailsCodeScanIdTypeNotSupported` is now `IdentityVerificationDetailsCodeScanIDTypeNotSupported`
  * `BitcointReceiver` resource where `BitcoinUri` is now `BitcoinURI`.
  * `IssuingAuthorization` resource where `NetworkId` is now `NetworkID`

r? @brandur-stripe 
cc @stripe/api-libraries

### CODE REVIEW

**Comment by remi-stripe** [comment]
Flagging that there's one left that I'm not sure how to fix
```
client/api.go:5:2: should not use dot imports
```

**Comment by remi-stripe** [comment]
Flagging that I got a "success" email for the build (2 really) though I expected it to fail since we now run the linter on the whole library.

**Comment by brandur-stripe** [comment]
> Flagging that there's one left that I'm not sure how to fix

It just doesn't like this line:

``` go
import (
	. "github.com/stripe/stripe-go"
```

It's considered poor practice to use `.` because you're polluting the package's global namespace rather than referring to names via a symbol. Try changing this to a:

``` go
import (
	stripe "github.com/stripe/stripe-go"
```

And putting `stripe.` in front of any references that broke.

> Flagging that I got a "success" email for the build (2 really) though I expected it to fail since we now run the linter on the whole library.

You still need to specify the `-set_exit_status` flag for Golint. It defaults to exiting with `0` even if linting problems were found.

**Comment by brandur-stripe** [comment]
And also: wow :) This is a serious piece of work!!

**Comment by remi-stripe** [comment]
@brandur-stripe ha I tried a few things but did not think to rename the .! Thanks for the quick answer.

PTAL

**Comment by remi-stripe** [comment]
@brandur-stripe Thanks for the quick review! Just fixed all of those, PTAL!

**Comment by brandur-stripe** [comment]
Thanks Remi! LGTM.

**Comment by brandur-stripe** [comment]
Released as 38.0.0.

Well, I hate to do two major versions in one day, but I figure that we may as well release this one while very few people have picked up version 37.

**Pull request merged**
