### PR TITLE
Add app info to stripe-go

### PR DESCRIPTION
**Pull request by brandur-stripe**
Adds app info the Go libraries (the idea is already in PHP and Ruby).

r? @ob-stripe 
cc @stripe/api-libraries 

---

~~Note: currently targets the branch in #391 until that's merged.~~

### CODE REVIEW

**Comment by ob-stripe** [comment]
My Go-fu is very weak, but lgtm!

OOC, when instantiating an `AppInfo` struct, all three fields must be provided, but users can provide empty strings as values for `URL` and `Version`, right? If that's the case, do you think it might be worth clarifying this in the README?

**Comment by brandur-stripe** [comment]
Thanks @ob-stripe!

> OOC, when instantiating an AppInfo struct, all three fields must be provided, but users can provide empty strings as values for URL and Version, right? If that's the case, do you think it might be worth clarifying this in the README?

So that's basically true, but actually the user doesn't have to specify all three fields. They're allowed to do this:

```go
	appInfo := &stripe.AppInfo{
		Name: "MyAwesomePlugin",
	}
```

Which is why I need to make empty string checks while encoding. In the case where these values aren't passed, `URL` and `Value` will end up as the string type's "zero value", which is an empty string.

**Comment by ob-stripe** [comment]
Makes perfect sense, thanks for explaining!

**Comment by brandur-stripe** [comment]
NP!

Released this and the `X-Stripe-Client-User-Agent` change as 21.2.0.

**Pull request merged**
