### PR TITLE
Add support for `PaymentMethodData` on `PaymentIntent`

### PR DESCRIPTION
**Pull request by remi-stripe**
Similar to https://github.com/stripe/stripe-java/pull/1023

r? @richardm-stripe 
cc @stripe/api-libraries @ln-stripe

### CODE REVIEW

**Comment by si-m** [comment]
This would be nice to have 💪

**Comment by remi-stripe** [comment]
rebased on latest master, self-approving and will merge once tests pass

**Comment by remi-stripe** [comment]
@si-m I just released this in 71.26.0 so you should now be all set!

**Comment by si-m** [comment]
@remi-stripe thats fast, thanks !

**Pull request merged**
